### ISSUE TITLE
Cannot hover

### ISSUE THREAD

**Issue by YuruiHong** [xiyaowong/coc-code-translate#1]
I think that by default vim does not provide a hover function, so the extension is not working. Is there any further configuration to be done?

**Comment by xiyaowong** [comment]
用这个插件应该都是说中文吧。这个插件直接hack的coc的hover，安装之后直接用coc自带的hover方法就可以了。结果在最下面

**Comment by YuruiHong** [comment]
如果使用coc的hover会显示[coc.nvim]: Error on notification "doHover": hover provider not found for current buffer, your language server doesn't support it.

**Comment by xiyaowong** [comment]
晚点看看

**Comment by YuruiHong** [comment]
补充：似乎是没有装相应lsp插件的语言会出现此现象，也就是此插件发挥作用需要该语言已经有其他lsp插件

**Comment by xiyaowong** [comment]
@YuruiHong 
![image](https://user-images.githubusercontent.com/47070852/235902279-09e9a8b3-bed5-4d73-bf73-f4e5c34c0e32.png)
奇怪啊，我这随便建个文件都有

**Comment by YuruiHong** [comment]
查看了coc.nvim的日志，相关报错如下：

```
2023-05-03T21:50:43.845 ERROR (pid:1049386) [attach] - Error on notification doHover Error: hover provider not found for current buffer, your language server doesn't support it.
    at Handler.checkProvider (/home/hyr/.vim/dein/repos/github.com/neoclide/coc.nvim/build/index.js:83220:17)
    at HoverHandler.onHover (/home/hyr/.vim/dein/repos/github.com/neoclide/coc.nvim/build/index.js:78565:22)
[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
    at async Plugin.cocAction (/home/hyr/.vim/dein/repos/github.com/neoclide/coc.nvim/build/index.js:83527:16)
    at async EventEmitter.<anonymous> (/home/hyr/.vim/dein/repos/github.com/neoclide/coc.nvim/build/index.js:83638:15)
```

**Comment by xiyaowong** [comment]
@YuruiHong 你好，不知道你还在使用这个插件吗？我今天想起来这个issue，已经修复了。
